import type { PlaylistsInfo } from '@/types/playlist';

export const playlists: PlaylistsInfo = {
  '1': {
    id: '1',
    name: 'Summer Vibes',
    description: 'Feel the summer vibes with this upbeat playlist.',
    songs: [
      {
        id: '1',
        title: 'Summer Nights',
        artists: ['The Beach Boys'],
        album: 'Summer Dreams',
        image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745',
        releaseDate: 'June 15, 2023',
        addedOn: 'July 1, 2023',
        duration: '3:45',
      },
      {
        id: '2',
        title: 'Sunset Vibes',
        artists: ['Tropical Waves'],
        album: 'Beach Life',
        image: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea',
        releaseDate: 'May 20, 2023',
        addedOn: 'June 25, 2023',
        duration: '4:20',
      },
    ],
  },
  '2': {
    id: '2',
    name: 'Workout Mix',
    description: 'Get pumped with this high-energy workout mix.',
    songs: [
      {
        id: '1',
        title: 'Summer Nights',
        artists: ['The Beach Boys'],
        album: 'Summer Dreams',
        image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745',
        releaseDate: 'June 15, 2023',
        addedOn: 'July 1, 2023',
        duration: '3:45',
      },
      {
        id: '2',
        title: 'Sunset Vibes',
        artists: ['Tropical Waves'],
        album: 'Beach Life',
        image: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea',
        releaseDate: 'May 20, 2023',
        addedOn: 'June 25, 2023',
        duration: '4:20',
      },
    ],
  },
  '3': {
    id: '3',
    name: 'Chill Beats',
    description: 'Relax and unwind with these chill beats.',
    songs: [
      {
        id: '1',
        title: 'Summer Nights',
        artists: ['The Beach Boys'],
        album: 'Summer Dreams',
        image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745',
        releaseDate: 'June 15, 2023',
        addedOn: 'July 1, 2023',
        duration: '3:45',
      },
      {
        id: '2',
        title: 'Sunset Vibes',
        artists: ['Tropical Waves'],
        album: 'Beach Life',
        image: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea',
        releaseDate: 'May 20, 2023',
        addedOn: 'June 25, 2023',
        duration: '4:20',
      },
    ],
  },
  '4': {
    id: '4',
    name: 'More Songs that i like to sing in the shower and lets see if it fits or not to make the test',
    description: 'Sing along to your favorite shower songs.',
    songs: [
      {
        id: '1',
        title: 'Summer Nights',
        artists: ['The Beach Boys'],
        album: 'Summer Dreams',
        image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745',
        releaseDate: 'June 15, 2023',
        addedOn: 'July 1, 2023',
        duration: '3:45',
      },
      {
        id: '2',
        title: 'Sunset Vibes',
        artists: ['Tropical Waves'],
        album: 'Beach Life',
        image: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea',
        releaseDate: 'May 20, 2023',
        addedOn: 'June 25, 2023',
        duration: '4:20',
      },
    ],
  },
  '5': {
    id: '5',
    name: 'Reggaeton Hits',
    description: 'Dance to the hottest reggaeton hits.',
    songs: [
      {
        id: '1',
        title: 'Despacito',
        artists: ['Luis Fonsi'],
        album: 'Vida',
        image: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea',
        releaseDate: 'January 13, 2017',
        addedOn: 'February 1, 2017',
        duration: '3:47',
      },
      {
        id: '2',
        title: 'Taki Taki',
        artists: ['DJ Snake'],
        album: 'Carte Blanche',
        image: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea',
        releaseDate: 'September 28, 2018',
        addedOn: 'October 5, 2018',
        duration: '3:32',
      },
      {
        id: '3',
        title: 'Con Calma',
        artists: ['Daddy Yankee'],
        album: 'Con Calma & Mis Grandes Éxitos',
        image: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea',
        releaseDate: 'January 24, 2019',
        addedOn: 'February 1, 2019',
        duration: '3:13',
      },
    ],
  },
  '6': {
    id: '6',
    name: 'EDM Party',
    description: 'Party all night with these EDM tracks.',
    songs: [
      {
        id: '1',
        title: 'Titanium',
        artists: ['David Guetta'],
        album: 'Nothing but the Beat',
        image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4',
        releaseDate: 'August 8, 2011',
        addedOn: 'September 1, 2011',
        duration: '4:05',
      },
      {
        id: '2',
        title: 'Animals',
        artists: ['Martin Garrix'],
        album: 'Animals',
        image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4',
        releaseDate: 'June 17, 2013',
        addedOn: 'July 1, 2013',
        duration: '5:03',
      },
      {
        id: '3',
        title: 'Wake Me Up',
        artists: ['Avicii'],
        album: 'True',
        image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4',
        releaseDate: 'June 17, 2013',
        addedOn: 'July 1, 2013',
        duration: '5:03',
      },
      {
        id: '4',
        title: 'Take On Me',
        artists: ['a-ha'],
        album: 'Hunting High and Low',
        image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4',
        releaseDate: 'October 19, 1984',
        addedOn: 'November 1, 1984',
        duration: '3:48',
      },
      {
        id: '5',
        title: 'Billie Jean',
        artists: ['Michael Jackson'],
        album: 'Thriller',
        image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4',
        releaseDate: 'January 2, 1983',
        addedOn: 'February 1, 1983',
        duration: '4:54',
      },
      {
        id: '6',
        title: "Sweet Child O' Mine",
        artists: ["Guns N' Roses"],
        album: 'Appetite for Destruction',
        image: 'https://images.unsplash.com/photo-1511671782779-c97dd27a1d4',
        releaseDate: 'June 17, 2013',
        addedOn: 'July 1, 2013',
        duration: '5:03',
      },
    ],
  },
};
